[package]
authors = ["Dean Karn <dean.karn@gmail.com>"]
name = "rpc-lib"
version = "1.0.0"
license = "MIT"

[dependencies]
reqwest = "0.8.6"
serde = "1.0.66"
serde_derive = "1.0.66"
serde_json = "1.0.20"
